"""add clerk_user_id to pieces

Revision ID: d9d083e4b5f8
Revises: 0001
Create Date: 2026-05-11 16:04:13.805552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9d083e4b5f8'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pieces', sa.Column('clerk_user_id', sa.String(length=128), nullable=True))
    op.drop_index(op.f('ix_pieces_embedding'), table_name='pieces', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_pieces_status'), table_name='pieces')
    op.create_index(op.f('ix_pieces_clerk_user_id'), 'pieces', ['clerk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pieces_clerk_user_id'), table_name='pieces')
    op.create_index(op.f('ix_pieces_status'), 'pieces', ['status'], unique=False)
    op.create_index(op.f('ix_pieces_embedding'), 'pieces', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('pieces', 'clerk_user_id')
    # ### end Alembic commands ###
